import { BreakerIndexObject } from "./types";

/**
 * Returns true if the provided error was generated by an circuit breaker. It will be false
 * if the error came from the action itself.
 * @private
 * @param {BreakerIndexObject} indexObject Index object for the circuit breaker.
 * @returns {string} Index string for the circuit breaker
 */
export const getBreakerIndex = (indexObject: BreakerIndexObject): string => {
    const { requestURL, requestMethod } = indexObject;
    return `${requestMethod}_${requestURL}`;
};
